require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TestObjectsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # TestObject. As you add validations to TestObject, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TestObjectsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all test_objects as @test_objects" do
      test_object = TestObject.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:test_objects)).to eq([test_object])
    end
  end

  describe "GET show" do
    it "assigns the requested test_object as @test_object" do
      test_object = TestObject.create! valid_attributes
      get :show, {:id => test_object.to_param}, valid_session
      expect(assigns(:test_object)).to eq(test_object)
    end
  end

  describe "GET new" do
    it "assigns a new test_object as @test_object" do
      get :new, {}, valid_session
      expect(assigns(:test_object)).to be_a_new(TestObject)
    end
  end

  describe "GET edit" do
    it "assigns the requested test_object as @test_object" do
      test_object = TestObject.create! valid_attributes
      get :edit, {:id => test_object.to_param}, valid_session
      expect(assigns(:test_object)).to eq(test_object)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TestObject" do
        expect {
          post :create, {:test_object => valid_attributes}, valid_session
        }.to change(TestObject, :count).by(1)
      end

      it "assigns a newly created test_object as @test_object" do
        post :create, {:test_object => valid_attributes}, valid_session
        expect(assigns(:test_object)).to be_a(TestObject)
        expect(assigns(:test_object)).to be_persisted
      end

      it "redirects to the created test_object" do
        post :create, {:test_object => valid_attributes}, valid_session
        expect(response).to redirect_to(TestObject.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved test_object as @test_object" do
        post :create, {:test_object => invalid_attributes}, valid_session
        expect(assigns(:test_object)).to be_a_new(TestObject)
      end

      it "re-renders the 'new' template" do
        post :create, {:test_object => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested test_object" do
        test_object = TestObject.create! valid_attributes
        put :update, {:id => test_object.to_param, :test_object => new_attributes}, valid_session
        test_object.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested test_object as @test_object" do
        test_object = TestObject.create! valid_attributes
        put :update, {:id => test_object.to_param, :test_object => valid_attributes}, valid_session
        expect(assigns(:test_object)).to eq(test_object)
      end

      it "redirects to the test_object" do
        test_object = TestObject.create! valid_attributes
        put :update, {:id => test_object.to_param, :test_object => valid_attributes}, valid_session
        expect(response).to redirect_to(test_object)
      end
    end

    describe "with invalid params" do
      it "assigns the test_object as @test_object" do
        test_object = TestObject.create! valid_attributes
        put :update, {:id => test_object.to_param, :test_object => invalid_attributes}, valid_session
        expect(assigns(:test_object)).to eq(test_object)
      end

      it "re-renders the 'edit' template" do
        test_object = TestObject.create! valid_attributes
        put :update, {:id => test_object.to_param, :test_object => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested test_object" do
      test_object = TestObject.create! valid_attributes
      expect {
        delete :destroy, {:id => test_object.to_param}, valid_session
      }.to change(TestObject, :count).by(-1)
    end

    it "redirects to the test_objects list" do
      test_object = TestObject.create! valid_attributes
      delete :destroy, {:id => test_object.to_param}, valid_session
      expect(response).to redirect_to(test_objects_url)
    end
  end

end
